TicketManagementApp/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TicketManagementApp.Models
{
    public class Ticket
    {
        [Key]
        public int TicketID { get; set; }
        [Display(Name ="واحد")]
        public int? UserGroupID { get; set; }
        [Display(Name ="نوع تیکت")]
        public int TicketGroupID { get; set; }
        [Display(Name = "کاربر")]
        public int AccountID { get; set; }
        [Display(Name ="موضوع تیکت")]
        public string TicketSubject { get; set; }
        [Display(Name ="شرح تیکت")]
        [DataType(DataType.MultilineText)]
        public string TicketDescription { get; set; }
        [Display(Name ="ضمیمه")]
        [DataType(DataType.Upload)]
        public string TicketAttachment {  get; set; }
        
        [Display(Name ="وضعیت تیکت")]
        public string TicketStatus { get; set; }
        [Display(Name ="تاریخ ایجاد تیکت")]
        public DateTime TicketDate { get; set; }
        [Display(Name ="کد رهگیری")]
        public string TrackCode { get; set; }
        [Display(Name ="واحد گیرنده")]
        public int? DepartmentId { get; set; }
        public Ticket()
        {
            
        }
        public virtual TicketGroup TicketGroup { get; set; }
        public virtual Accounts Account { get; set; }
        public virtual List<TicketReply> TicketReply { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual Department Department { get; set; }
    }
}

TicketManagementApp/Models/TicketReply.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TicketManagementApp.Models
{
    public class TicketReply
    {
        [Key]
        public int ReplyId { get; set; }

        [Display(Name ="شماره تیکت")]
        public int TicketID { get; set; }

        [Display(Name = "پاسخ دعنده")]
        public int? AccountID { get; set; }

        [Required]
        public string Text { get; set; }

        [Display(Name ="ضمیمه")]
        [DataType(DataType.Upload)]
        public string TicketReplyAttachment {  get; set; }

        [Required]
        [Display(Name ="تاریخ پاسخ")]
        public DateTime ReplyDate { get; set; }

        public TicketReply()
        {
            
        }
        public virtual Ticket Ticket { get; set; }
        public virtual Accounts Accounts { get; set; }
    }
}

TicketManagementApp/Areas/Admin/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TicketManagementApp.Context;
using TicketManagementApp.Models;
using TicketManagementApp.Repositories;
using TicketManagementApp.Repositories.Services;

namespace TicketManagementApp.Areas.Admin.Controllers
{
    public class TicketsController : Controller
    {
        private ITicketRepo ticketRepository;
        private IAccountRepo accountRepository;
        private IMessageRepository emailService;

        public TicketsController()
        {
            ticketRepository = new TicketService();
            accountRepository = new AccountService();
            
        }
        // GET: Admin/Tickets
        public ActionResult Index()
        {
            //var tickets = ticket.Tickets.Include(t => t.TicketGroup);
            return View(ticketRepository.GetAllTickets());
        }

        // GET: Admin/Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = ticketRepository.GetTicketById(id.Value);
            //ticket.TicketStatus = TicketStatusEnum.READ.ToString();
            
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Admin/Tickets/Create
        public ActionResult Create()
        {
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle");
            ViewBag.UserGroupID = new SelectList(new UserGroupService().GetAllUserGroups(), "UserGroupID", "UserGroupTitle");

            return View();
        }

        // POST: Admin/Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TicketID,TicketGroupID,TicketSubject,TicketDescription")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticketRepository.InsertTicket(ticket);
                ticketRepository.Save();
                return RedirectToAction("Index");
            }

            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle", ticket.TicketGroupID);
            return View(ticket);
        }

        // GET: Admin/Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = ticketRepository.GetTicketById(id.Value);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle", ticket.TicketGroupID);
            return View(ticket);
        }

        // POST: Admin/Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TicketID,TicketGroupID,TicketSubject,TicketDescription")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticketRepository.UpdateTicket(ticket);
                ticketRepository.Save();
                return RedirectToAction("Index");
            }
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle", ticket.TicketGroupID);
            return View(ticket);
        }

        // GET: Admin/Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = ticketRepository.GetTicketById(id.Value);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Admin/Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = ticketRepository.GetTicketById(id);
            ticketRepository.DeleteTicket(ticket);
            ticketRepository.Save();
            return RedirectToAction("Index");
        }
        //test
        public ActionResult SendTestEmail()
        {
            emailService = new EmailService("test","تیکت ثبت شده است", "ticketing@kavehlogistics.com");
            emailService.Send();
            return RedirectToAction("Index");
        }
        //test
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ticketRepository.Dispose();
            }
            base.Dispose(disposing);
        }


        //searchbox test
        [HttpPost]
        public ActionResult Search(string searchString)
        {
            var model = ticketRepository.GetAllTickets().Where(item => item.TrackCode == searchString);
            return View("Index",model);
        }
    }
}

TicketManagementApp/Controllers/TicketController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TicketManagementApp.Context;
using TicketManagementApp.Models;
using TicketManagementApp.Repositories;
using TicketManagementApp.Repositories.Services;

namespace TicketManagementApp.Controllers
{
    public class TicketController : Controller
    {
        private TkContext _tkContext;
        private ITicketReplyRepo _ticketReplyRepo;
        private ITicketRepo _ticketRepo;

        public TicketController()
        {
            _tkContext = new TkContext();
            _ticketRepo = new TicketService();
            _ticketReplyRepo = new TicketReplyService();
        }
        // GET: Ticket
        public ActionResult Index()
        {
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle");
            ViewBag.UserGroupID = new SelectList(new UserGroupService().GetAllUserGroups(), "UserGroupID", "UserGroupTitle");

            return View();
        }
        public ActionResult TicketView(int? page)
        {
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle");
            int departmentId = Int32.Parse(Session["DepartmentId"].ToString());
            ViewBag.UnreadCounterValue = _ticketRepo.GetAllTickets().Where(i => i.TicketStatus == "در انتظار بررسی" && i.DepartmentId == departmentId).Count();
            int pageNumber = (page ?? 1);
            
            return View(_ticketRepo.GetAllTickets().OrderByDescending(i=>i.TicketID).ToList().ToPagedList(pageNumber, 15));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include ="TicketID,TicketGroupID,TicketSubject,TicketDescription,TicketAttachment,TicketStatus")] Ticket ticket
            , HttpPostedFileBase TicketAttachmentUpload)
        {
            var result = new {isValid= true};
            
            if (ModelState.IsValid)
            {

                ticket.TicketStatus = "در انتظار بررسی";
                ticket.TicketDate = DateTime.Now;
                ticket.AccountID = Int32.Parse(Session["AccountID"].ToString());
                
                if(TicketAttachmentUpload != null)
                {
                    ticket.TicketAttachment = Guid.NewGuid() + Path.GetExtension(TicketAttachmentUpload.FileName);
                    TicketAttachmentUpload.SaveAs(Server.MapPath("/TicketAttachments/" + ticket.TicketAttachment));
                }

                _tkContext.Tickets.Add(ticket);
                _tkContext.SaveChanges();
                //await JS.InvokeVoidAsync("displayAlert");
                //return RedirectToAction("TicketView");
                return Json(result);
            }
            ViewBag.TicketGroupID = new SelectList(new TicketGroupService().GetAllTicketGroups(), "TicketGroupID", "TicketGroupTitle");
            ViewBag.IsSuccess = true;
            return View();
        }
        public ActionResult TicketReply(int? id)
        {
            if(id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Ticket ticket = _tkContext.Tickets.Find(id);
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TicketReply([Bind]Ticket ticket, string replyText, HttpPostedFileBase TicketReplyAttachmentUpload)
        {
            Ticket ticket1 = _tkContext.Tickets.Find(ticket.TicketID);
            if (ModelState.IsValid)
            {
                TicketReply reply = new TicketReply();
                reply.TicketID = ticket.TicketID;
                reply.Text = replyText;
                reply.AccountID = Int32.Parse(Session["AccountID"].ToString());
                reply.ReplyDate = DateTime.Now;
                if (TicketReplyAttachmentUpload != null)
                {
                    reply.TicketReplyAttachment = Guid.NewGuid() + Path.GetExtension(TicketReplyAttachmentUpload.FileName);
                    TicketReplyAttachmentUpload.SaveAs(Server.MapPath("/TicketAttachments/" + reply.TicketReplyAttachment));
                }
                _ticketReplyRepo.InsertTicketReply(reply);
                _ticketReplyRepo.Save();
                ticket1.TicketReply.Add(reply);
                _ticketRepo.UpdateTicket(ticket1);
                _ticketRepo.Save();
            }
            return RedirectToAction("TicketView");
            //return View(ticket1);
        }
        public ActionResult TicketDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = _ticketRepo.GetTicketById(id.Value);
            
            if(ticket.TicketStatus == "در انتظار بررسی")
                ticket.TicketStatus = "در حال بررسی";
            
            _ticketRepo.UpdateTicket(ticket);
            _ticketRepo.Save();
            if (ticket == null)
                return HttpNotFound();
            return View(ticket);
        }

        public ActionResult CloseTicket(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = _ticketRepo.GetTicketById(id.Value);
            ticket.TicketStatus = "بسته شده";
            _ticketRepo.UpdateTicket(ticket);
            _ticketRepo.Save();
            return RedirectToAction("TicketView");

        }

        [HttpPost]
        public ActionResult Search(string searchString)
        {
            if ((searchString.IsNullOrWhiteSpace()))
            {
                return RedirectToAction("TicketView");
            }
            int pageNumber = 1;
            var model = _ticketRepo.GetAllTickets().Where(item => item.TrackCode == searchString).ToPagedList(pageNumber, 15);
            return View("TicketView", model);
        }
    }
}

TicketManagementApp/Views/Ticket/Index.cshtml
@model TicketManagementApp.Models.Ticket

@{
    //Layout = "~/Views/Shared/_DefaultLayout.cshtml";
    Layout = "~/Views/Shared/_DefPage1.cshtml";
    ViewBag.Title = "Create";
}

<!--<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Bootstrap Admin Template</title>-->
<!-- Bootstrap Core /Content/css -->
<!--<link href="~/Content/css/bootstrap.min.css" rel="stylesheet">-->
<!-- Custom /Content/css -->
<!--<link href="~/Content/css/sb-admin.css" rel="stylesheet">-->
<!-- Morris Charts /Content/css -->
<!--<link href="~/Content/css/plugins/morris.css" rel="stylesheet">-->
<!-- Custom Fonts -->
<!--<link href="~/Content/font-awesome/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond./Content/js/1.4.2/respond.min.js"></script>
<![endif]-->
<!--</head>-->
<!--<head>-->
@*<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />*@
@*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
<!--</head>-->


@using (Html.BeginForm("Index", "Ticket", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="">
        <h4>تیکت جدید</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-row">
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.TicketSubject, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.TicketSubject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketSubject, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.TicketGroupID, "نوع تیکت", htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("TicketGroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Account.UserGroupID, "واحد", htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("UserGroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Account.UserGroupID, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TicketDescription, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.TicketDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mx-sm-3">
            @Html.LabelFor(model => model.TicketAttachment, htmlAttributes: new { @class = "control-label" })

            @*@Html.EditorFor(model => model.TicketAttachment, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.TicketAttachment, "", new { @class = "text-danger" })
            <input class="form-control" type="file" name="TicketAttachmentUpload" />

        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.TicketStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TicketStatus, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TicketStatus, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <input id="ticketSubmit" class="btn btn-danger" type="submit" value="ارسال تیکت" />
        </div>
    </div>
}

@section s{
    <script>
        $(document).ready(function () {
            alert("s");
        });

        function onSuccess(res) {
            if (res.isValid)
                alert("valid");
        }
    </script>
}

TicketManagementApp/Views/Ticket/TicketReply.cshtml
@model TicketManagementApp.Models.Ticket

@{
    ViewBag.Title = "TicketReply";
    Layout = "~/Views/Shared/_DefPage1.cshtml";
}

<body>
    <div>
        <h4 class="text-center">اطلاعات تیکت</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                ایجاد کننده تیکت
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Account.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketGroup.TicketGroupTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketGroup.TicketGroupTitle)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketSubject)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketSubject)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketDescription)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketAttachment)
            </dt>

            <dd>
                <a href="~/TicketAttachments/@Model.TicketAttachment">@Html.DisplayFor(model => model.TicketAttachment)</a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketStatus)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketStatus)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketDate)
            </dd>

        </dl>


        @* reply box *@
        <div class="container-fluid">
            <div>
                @using (Html.BeginForm("TicketReply", "Ticket", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                <div class="form-horizontal bg-warning p-4">
                    <h4>پاسخ به تیکت</h4>
                    <hr />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div hidden="true" class="form-group m-3">
                        @Html.LabelFor(model => model.TicketID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TicketID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TicketID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div  class="form-group m-3">
                        @Html.LabelFor(model => model.TicketSubject, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TicketSubject, new { htmlAttributes = new { @class = "form-control",@disabled= "disabled" } })
                            @Html.ValidationMessageFor(model => model.TicketSubject, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group m-3">
                        @Html.LabelFor(model => model.TicketDescription, htmlAttributes: new { @class = "control-label col-md-3 " })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TicketDescription, new { htmlAttributes = new { @class = "form-control" , @disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.TicketDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">پاسخ به تیکت</label>
                        @*@Html.LabelFor(model => model.TicketReply, htmlAttributes: new { @class = "control-label col-md-3 " })*@
                        <div class="col-md-10">
                            <input class="form-control" type="text" name="replyText" />
                        </div>
                    </div>

                    <div class="form-group">

                        <input class="btn btn-success" type="submit" value="پاسخ به تیکت" />
                        @*@Html.ActionLink("پاسخ", "TicketReplyPost", new {id = Model.TicketID}, htmlAttributes: new { @class = "btn btn-success text-white" , @type="submit"})*@
                        @Html.ActionLink("بازگشت", "TicketView", "TicketView", htmlAttributes: new { @class = "btn btn-danger text-white" })

                    </div>

                    <div class="form-group">


                    </div>
                </div>
                }
            </div>
        </div>
        @* end of reply box *@
    </div>
    <p>
        @*@Html.ActionLink("Edit", "Edit", new { id = Model.TicketID }) |*@
        @*@Html.ActionLink("بازگشت", "TicketView", "", htmlAttributes: new {@class="btn btn-danger"})*@
    </p>
</body>